### PR TITLE
refactor: DefaultErrorStrategy

### PR DESCRIPTION
**Pull request by dawciobiel**
refactor: DetailedErrorStrategy
refactor: ErrorResponseDTO
refactor: ErrorResponseListDescriptionDTO
refactor: ErrorStrategy
refactor: FinancialTransactionServiceImplTest
refactor: GlobalExceptionHandler
refactor: WalletController
refactor: WalletCreateControllerTest
refactor: WalletCreateServiceImplTest
refactor: WalletDeleteControllerTest
refactor: WalletDeleteServiceImplTest
refactor: WalletGetControllerTest
refactor: WalletGetServiceImplTest
refactor: WalletUpdateControllerTest
refactor: WalletUpdateServiceImplTest

### CODE REVIEW

**Review by odzio33 — APPROVED** [review]
looks good for me

**Review by Iwona007 — DISMISSED** [review]

**Review by DawidStuzynski — DISMISSED** [review]
Looks good for me

**Review by dawciobiel — COMMENTED** [review]
Looks good for me. Requesting for code-review and approval.

**Review by mirekgab — APPROVED** [review]

**Review by odzio33 — APPROVED** [review]
Looks good for me

**Pull request merged**
