### PR TITLE
refactor: Rename fields of the class FinancialTransaction

### PR DESCRIPTION
**Pull request by dawciobiel**
refactor: Rename fields of the class FinancialTransaction

### CODE REVIEW

**Review by odzio33 — APPROVED** [review]
Looks good for me

**Review by DawidStuzynski — DISMISSED** [review]
Looks good for me

**Review by Iwona007 — DISMISSED** [review]

**Review by odzio33 — APPROVED** [review]
Looks good for me

**Review by odzio33 — APPROVED** [review]
Looks good for me

**Review by Krisu93 — APPROVED** [review]
Good for me

**Pull request merged**
